openapi: 3.0.1
info:
  title: Car rental
  description: Car rental service REST API
  contact:
        name:  Ira
        email: iryna.matseiko.knm.2019@lpnu.ua
  version: 1.0.0
servers:
  - url: 'https://сar_rental.swagger.io/api/v2'
  - url: 'http://сar_rental.swagger.io/api/v2'

tags:
- name: user
  description: Operations with users
- name: car
  description: Operations with car
- name: booking
  description: Car booking

paths:
  /user:
    post:
      tags:
        - user 
      description: Operations with users
      summary: Operations with users
      operationId: createuser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_user'
      responses:
        '300':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
      - api_key: [ ]
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
  /user/administrator:
    post:
      tags:
        - user
      summary: Admin
      operationId: createadmin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_user'
      responses:
        '300':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
        - write:administrator
        - read:administrator
      - api_key: [ ]
  '/user/{id_user}':
    get:
      tags:
        - user
      summary: Get user data
      operationId: getdata
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '301':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - read:passenger
      - api_key: [ ]
    put:
      tags:
        - user
      summary: Update user data
      operationId: Updatedata 
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_user'
      responses:
        '301':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
      - api_key: [ ]
    delete:
      tags:
        - user
      summary: Delete user
      operationId: deleteuser 
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        - car_auth:
          - write:administrator
          - read:administrator
        - api_key: [ ]
  /car:
    post:
      tags:
        - car
      summary: Add a new car
      operationId: addcar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_car'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/car'
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:administrator
        - read:administrator
      - api_key: [ ]
    get:
      tags:
        - car
      summary: Get all the cars
      operationId: getcars
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/car'
                nullable: false
        '403':
          description: Car not found
          content: {}
        '402':
          description: User not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
      - api_key: [ ]
  '/car/{id_car}':
    get:
      tags:
        - car
      summary: Get the car with such id
      operationId: getcarid
      parameters:
        - name: id_car
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/car'
        '401':
          description: Only administrator can do that
          content: {}
        '403':
          description: Car not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:administrator
        - read:administrator
      - api_key: [ ]
    put:
      tags:
        - car
      summary: Update the car with such id
      operationId: Updatecar
      parameters:
        - name: id_car
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_car'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/car'
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        '403':
          description: Car not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:administrator
        - read:administrator
      - api_key: [ ]
    delete:
      tags:
        - car
      summary: Delete the car with such id
      operationId: deletecar 
      parameters:
        - name: id_car
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content: {}
        '400':
          description: User is not authorized
          content: {}
        '401':
          description: Only administrator can do that
          content: {}
        '402':
          description: User not found
          content: {}
        '403':
          description: Car not found
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        - car_auth:
          - write:administrator
          - read:administrator
        - api_key: [ ]
  /booking:
    post:
      tags:
        - booking
      summary: Create a new booking
      operationId: creatbooking 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_booking'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking'
        '400':
          description: User is not authorized
          content: {}
        '404':
          description: Only passenger can do that
          content: {}
        '405':
          description: The car was booked by another user
          content: {}
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
      - api_key: [ ]
    get:
      tags:
        - booking
      summary: Get everything that is not booked
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/booking'
                nullable: false
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
      - car_auth:
        - write:passenger
        - read:passenger
      - api_key: [ ]

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        first name:
          type: string
        last name:
          type: string
        birthday:
          type: string
          format: date
        email:
          type: string
        role:
          type: string
      nullable: false
    car:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
      nullable: false
    booking:
      type: object
      properties:
        user id:
          type: string
        car id:
          type: string
        booking from:
          type: integer
          format: date
        booking until:
          type: integer
          format: date
        id:
          type: string
      nullable: false
    create_user:
      type: object
      properties:
        first name:
          type: string
        last name:
          type: string
        birthday:
          type: string
          format: date
        email:
          type: string
        role:
          type: string
      nullable: false
    create_car:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
      nullable: false
    create_booking:
      type: object
      properties:
        user id:
          type: string
        car id:
          type: string
        booking from:
          type: integer
          format: date
        booking until:
          type: integer
          format: date
      nullable: false
    error:
      required:
        - code
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

            
  securitySchemes:
    car_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://car.swagger.io/oauth/dialog
          scopes:
            write:passenger: modify user in your account
            read:passenger: read your pets
            write:administrator: modify user in your account
            read:administrator: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
